# Generated by Django 2.1.5 on 2019-02-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Enter step title')),
                ('description', models.TextField(help_text='Enter step description')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
