# Generated by Django 2.1.5 on 2019-02-12 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', help_text='Enter medication name')),
                ('category', models.TextField(help_text='Enter medication type')),
                ('initial_Dose', models.FloatField(help_text='Enter medication initial dose in mg')),
                ('maximum_Dose', models.FloatField(help_text='Enter medication maximum dose in mg')),
                ('titration', models.TextField(help_text='Enter medication titration information')),
                ('comments', models.TextField(help_text='Enter comments about medication')),
                ('side_Effects', models.TextField(help_text='Enter side effects for medication')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.TextField(help_text='Enter patient first name and middle initial')),
                ('last_Name', models.TextField(help_text='Enter patient last name')),
                ('DOB', models.DateField(help_text='Enter patient date of birth')),
                ('address', models.TextField(help_text='Enter patient current address')),
                ('email', models.EmailField(help_text='Enter patient current email', max_length=254)),
                ('phone', models.TextField(help_text='Enter patient current phone number')),
                ('next_Visit', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enter the next visit date and time of the patient if applicable')),
                ('notes', models.TextField(help_text='Enter any prescriber notes about patient')),
            ],
            options={
                'ordering': ['last_Name', 'first_Name'],
            },
        ),
        migrations.CreateModel(
            name='Prescriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', help_text='Enter step title')),
                ('description', models.TextField(help_text='Enter step description')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', help_text='Enter disorder treatment type title')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
