# Generated by Django 2.1.5 on 2019-02-12 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='treatment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='application.Treatment'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.TextField(help_text='Enter medication name'),
        ),
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.TextField(help_text='Enter step title'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='name',
            field=models.TextField(help_text='Enter disorder treatment type title'),
        ),
    ]
