# Generated by Django 2.1.5 on 2019-02-11 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='treatment',
        ),
    ]
