# Generated by Django 2.1.5 on 2019-02-12 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0002_auto_20190212_0412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescriber',
            options={'ordering': ['user']},
        ),
        migrations.RemoveField(
            model_name='prescriber',
            name='name',
        ),
        migrations.AddField(
            model_name='prescriber',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
