# Generated by Django 2.1.5 on 2019-02-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20190209_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Enter medication name')),
                ('category', models.TextField(help_text='Enter medication type')),
                ('init_dose', models.FloatField(help_text='Enter medication initial dose in mg')),
                ('max_dose', models.FloatField(help_text='Enter medication maximum dose in mg')),
                ('titration', models.TextField(help_text='Enter medication titration information')),
                ('comments', models.TextField(help_text='Enter comments about medication')),
                ('side_effects', models.TextField(help_text='Enter side effects for medication')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(help_text='Enter patient first name and middle initial')),
                ('lname', models.TextField(help_text='Enter patient last name')),
                ('dob', models.DateField(help_text='Enter patient date of birth')),
                ('address', models.TextField(help_text='Enter patient current address')),
                ('email', models.EmailField(help_text='Enter patient current email', max_length=254)),
                ('phone', models.TextField(help_text='Enter patient current phone number')),
                ('notes', models.TextField(help_text='Enter any prescriber notes about patient')),
            ],
            options={
                'ordering': ['lname', 'fname'],
            },
        ),
    ]
