# Generated by Django 2.1.7 on 2019-02-24 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20190223_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phq9s',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.Phq9'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
