# Generated by Django 2.1.5 on 2019-02-12 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20190212_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='current_Step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.Step'),
        ),
        migrations.AddField(
            model_name='patient',
            name='prescriber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.Prescriber'),
        ),
    ]
