# Generated by Django 2.1.5 on 2019-02-10 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0003_medication_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_Name', 'first_Name']},
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='init_dose',
            new_name='initial_Dose',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='max_dose',
            new_name='maximum_Dose',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='side_effects',
            new_name='side_Effects',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='dob',
            new_name='DOB',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='fname',
            new_name='first_Name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='lname',
            new_name='last_Name',
        ),
        migrations.AddField(
            model_name='patient',
            name='next_Visit',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enter the next visit date and time of the patient if applicable'),
            preserve_default=False,
        ),
    ]
