# Generated by Django 2.1.7 on 2019-02-24 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20190224_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='phq9s',
        ),
        migrations.AddField(
            model_name='phq9',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.Patient'),
        ),
    ]
