# Generated by Django 2.1.5 on 2019-02-10 23:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20190210_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='next_Visit',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enter the next visit date and time of the patient if applicable'),
        ),
    ]
