# Generated by Django 2.1.5 on 2019-03-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20190224_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.TextField(help_text='Enter medication name', max_length=25),
        ),
    ]
