# Generated by Django 2.1.5 on 2019-02-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20190212_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medications',
            field=models.ManyToManyField(to='application.Medication'),
        ),
    ]
