# Generated by Django 2.1.5 on 2019-02-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_patient_medications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='category',
            field=models.CharField(help_text='Enter medication type', max_length=50),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(help_text='Enter medication name', max_length=25),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(help_text='Enter patient current address', max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(help_text='Enter patient current email', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_Name',
            field=models.CharField(help_text='Enter patient first name and middle initial', max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_Name',
            field=models.CharField(help_text='Enter patient last name', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(help_text='Enter patient current phone number', max_length=20),
        ),
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.CharField(help_text='Enter step title', max_length=25),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='name',
            field=models.CharField(help_text='Enter disorder treatment type title', max_length=25),
        ),
    ]
