# Generated by Django 2.1.5 on 2019-03-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20190301_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.TextField(help_text='Enter medication name'),
        ),
    ]
