# Generated by Django 2.1.7 on 2019-03-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20190301_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(help_text='Enter patient current phone number', max_length=11),
        ),
    ]
