# Generated by Django 2.1.7 on 2019-03-11 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20190310_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='previous_step',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.Step'),
        ),
        migrations.AddField(
            model_name='step',
            name='transition',
            field=models.CharField(default='', help_text='Enter the transition to this step', max_length=50),
        ),
        migrations.AddField(
            model_name='step',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='step',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
