# Generated by Django 2.1.5 on 2019-02-17 06:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20190213_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phq9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('question_1', models.IntegerField()),
                ('question_2', models.IntegerField()),
                ('question_3', models.IntegerField()),
                ('question_4', models.IntegerField()),
                ('question_5', models.IntegerField()),
                ('question_6', models.IntegerField()),
                ('question_7', models.IntegerField()),
                ('question_8', models.IntegerField()),
                ('question_9', models.IntegerField()),
                ('question_10', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.RemoveField(
            model_name='medication',
            name='initial_Dose',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='maximum_Dose',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='side_Effects',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='current_Step',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='first_Name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_Name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='next_Visit',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='prescriber',
        ),
        migrations.AddField(
            model_name='medication',
            name='initial_dose',
            field=models.FloatField(default=0, help_text='Enter medication initial dose in mg'),
        ),
        migrations.AddField(
            model_name='medication',
            name='maximum_dose',
            field=models.FloatField(default=0, help_text='Enter medication maximum dose in mg'),
        ),
        migrations.AddField(
            model_name='medication',
            name='side_effects',
            field=models.TextField(default='', help_text='Enter side effects for medication'),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.Step'),
        ),
        migrations.AddField(
            model_name='patient',
            name='dob',
            field=models.DateField(default='', help_text='Enter patient date of birth'),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='', help_text='Enter patient first name and middle initial', max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='', help_text='Enter patient last name', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='next_visit',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enter the next visit date and time of the patient if applicable'),
        ),
    ]
