# Generated by Django 2.1.7 on 2019-03-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20190310_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='step',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
