# Generated by Django 2.1.7 on 2019-03-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20190310_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='name',
            field=models.CharField(default='', help_text='Enter step title', max_length=25),
        ),
    ]
