# Generated by Django 2.1.7 on 2019-03-14 03:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20190311_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='MDQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('question_1', models.BooleanField(default=False)),
                ('question_2', models.BooleanField(default=False)),
                ('question_3', models.BooleanField(default=False)),
                ('question_4', models.BooleanField(default=False)),
                ('question_5', models.BooleanField(default=False)),
                ('question_6', models.BooleanField(default=False)),
                ('question_7', models.BooleanField(default=False)),
                ('question_8', models.BooleanField(default=False)),
                ('question_9', models.BooleanField(default=False)),
                ('question_10', models.BooleanField(default=False)),
                ('question_11', models.BooleanField(default=False)),
                ('question_12', models.BooleanField(default=False)),
                ('question_13', models.BooleanField(default=False)),
                ('question_14', models.BooleanField(default=False)),
                ('question_15', models.IntegerField(default=5)),
                ('diagnosis', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.Patient')),
            ],
        ),
    ]
