# Generated by Django 2.1.7 on 2019-03-28 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_mdq'),
        ('application', '0007_auto_20190306_1234'),
    ]

    operations = [
    ]
