# Generated by Django 2.1.7 on 2019-04-03 00:48

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_merge_20190327_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Enter patient current phone number', max_length=11, region=None),
        ),
    ]
