# Generated by Django 2.1.7 on 2019-03-25 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_merge_20190315_1228'),
        ('application', '0010_merge_20190321_1915'),
    ]

    operations = [
    ]
