# Generated by Django 2.1.7 on 2019-03-27 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20190307_2012'),
        ('application', '0011_merge_20190325_1345'),
    ]

    operations = [
    ]
