# Generated by Django 2.1.7 on 2019-04-12 22:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20190402_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditAlgoForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter step title', max_length=25)),
                ('description', models.TextField(help_text='Enter step description')),
                ('transition', models.CharField(default='', help_text='Enter the transition to this step', max_length=50)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('previous_step', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.EditAlgoForm')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='date_prescribed',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
