# Generated by Django 2.1.7 on 2019-04-24 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_auto_20190412_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editalgoform',
            name='previous_step',
        ),
        migrations.DeleteModel(
            name='EditAlgoForm',
        ),
    ]
